version: 2
models:
- name: products
  meta:
    database: ilufzqee
    schema: public
    resource_type: model
  description: A description for the model
  columns:
  - name: product_id
    description: A description for the column
  - name: product_name
    description: A description for the column
  - name: category
    description: A description for the column
  - name: price
    description: A description for the column
  dependencies:
  - name: raw_products
    database: ilufzqee
    schema: public
    resource_type: source
