version: 2

sources:
  - name: public
    database: tpch
    schema: public
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier


